{
 "title": "Linux",
 "tags": [
  "server",
  "linux"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"node_exporter:9100\"}",
     "legendFormat": "node"
    }
   ]
  },
  {
   "title": "Node Load1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=\"node_exporter:9100\"}",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_time_seconds{instance=\"node_exporter:9100\"} - node_boot_time_seconds)"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=\"node_exporter:9100\", mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "Used RAM (%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"node_exporter:9100\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) * 100)/ node_memory_MemTotal_bytes"
    }
   ]
  },
  {
   "title": "Node Load15",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load15{instance=\"node_exporter:9100\"}",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Node Load5",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load5{instance=\"node_exporter:9100\"}",
     "labelSelector": "*",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node_exporter:9100\"}"
    }
   ]
  },
  {
   "title": "Total swap",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"node_exporter:9100\"}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg without (cpu)(irate(node_cpu_seconds_total{instance=\"node_exporter:9100\",mode!=\"idle\"}[5m])))"
    }
   ]
  },
  {
   "title": "Used Swap (%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"node_exporter:9100\"} - node_memory_SwapFree_bytes)* 100)/ node_memory_SwapTotal_bytes"
    }
   ]
  },
  {
   "title": "Memória",
   "type": "graph",
   "description": "Esse painel mostra a quantidade de memória utilizada pelo host",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"node_exporter:9100\"} - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) * 100)/ node_memory_MemTotal_bytes",
     "legendFormat": "used RAM"
    }
   ]
  },
  {
   "title": "Espaço em disco utilizado",
   "type": "graph",
   "description": "Esse painel mostra a quantidade de espaço em disco utilizado pelo host",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n (\n  node_filesystem_size_bytes{instance=\"node_exporter:9100\",device!~'tmpfs|rootfs|by-uuid',mountpoint!~\"/boot|/selinux\"} \n  - \n  node_filesystem_avail_bytes\n )\n*100\n)\n/ node_filesystem_size_bytes ",
     "legendFormat": "{{mountpoint}} "
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Esse painel mostra a quantidade de CPU utilizado pelo host",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{instance=\"node_exporter:9100\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "description": "Esse painel mostra a quantidade de processos em espera no host",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"node_exporter:9100\"}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Tráfego de rede",
   "type": "graph",
   "description": "Esse painel mostra a quantidade de dados trafegando pela rede do host",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=\"node_exporter:9100\"}[5m]) ",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "-increase(node_network_transmit_bytes_total{instance=\"node_exporter:9100\"}[5m])",
     "legendFormat": "{{device}}_out"
    }
   ]
  },
  {
   "title": "Taxa de transferência de dados",
   "type": "graph",
   "description": "Esse painel mostra a taxa de transferência de dados para cada device do host",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(node_disk_read_bytes_total{instance=\"node_exporter:9100\", device!~\"dm.*\"}[5m]) ",
     "legendFormat": "{{device}}_read",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "expr": "-increase(node_disk_written_bytes_total{instance=\"node_exporter:9100\", device!~\"dm.*\"}[5m])",
     "legendFormat": "{{device}}_write",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Número de processos de IO",
   "type": "graph",
   "description": "Esse gráfico demonstra a quantidade de processos de read e write no servidor.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "IO/second read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "increase(node_disk_reads_completed_total{instance=\"node_exporter:9100\", device!~\"dm.*\"}[5m])",
     "legendFormat": "{{ device}} reads"
    },
    {
     "expr": "-increase(node_disk_writes_completed_total{instance=\"node_exporter:9100\", device!~\"dm.*\"}[5m])",
     "legendFormat": "{{device}} writes"
    }
   ]
  }
 ]
}