# Generated by Django 2.0.8 on 2018-10-27 03:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(blank=True, max_length=140, null=True, verbose_name='Número do Reembolso')),
                ('last_update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado no Jarbas em')),
                ('year', models.IntegerField(db_index=True, verbose_name='Ano')),
                ('month', models.IntegerField(db_index=True, verbose_name='Mês')),
                ('date', models.DateField(db_index=True, verbose_name='Data')),
                ('congressperson_name', models.CharField(blank=True, db_index=True, max_length=140, null=True, verbose_name='Nome do Parlamentar')),
                ('expense_type', models.CharField(blank=True, max_length=140, null=True, verbose_name='Tipo da Despesa')),
                ('expense_details', models.CharField(blank=True, max_length=140, null=True, verbose_name='Descrição da Despesa')),
                ('supplier', models.CharField(max_length=256, verbose_name='Fornecedor')),
                ('cnpj_cpf', models.CharField(blank=True, db_index=True, max_length=14, null=True, verbose_name='CNPJ ou CPF')),
                ('reimbursement_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Valor do Reembolso')),
                ('probability', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='Probabilidade')),
                ('suspicions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Suspeitas')),
            ],
            options={
                'verbose_name': 'reembolso',
                'verbose_name_plural': 'reembolsos',
                'ordering': ('-year', '-date'),
            },
        ),
        migrations.AlterIndexTogether(
            name='reimbursement',
            index_together={('year', 'date', 'id')},
        ),
    ]
