FROM node:6.9.1
RUN npm install -g yarn
VOLUME /code
WORKDIR /code
COPY elm-package.json elm-package.json
COPY package.json package.json
COPY gulpfile.js gulpfile.js
RUN yarn install
COPY jarbas jarbas
CMD yarn assets
