FROM node:6.9.1
WORKDIR /code
RUN npm install -g yarn
COPY elm-package.json elm-package.json
COPY package.json package.json
COPY gulpfile.js gulpfile.js
COPY jarbas jarbas
COPY contrib/copyassets.sh contrib/copyassets.sh
RUN chmod +x contrib/copyassets.sh
RUN yarn install
VOLUME /assets
RUN yarn assets
CMD ["./contrib/copyassets.sh"]
