#!/usr/bin/bash

cp config.ini.example config.ini

pip install --upgrade -r requirements.txt
conda pip config --add channels conda-forge
conda install --yes --file conda_requirements.txt

if ! which unzip 1>/dev/null 2>/dev/null; then
    echo "The following executables are needed and were not found: unzip"
fi

echo "Downloading datasets (this might take several minutes depending on your internet connection)"

python ./src/fetch_datasets.py
