from itertools import chain

from rows.fields import FloatField

from jarbas.chamber_of_deputies.fields import DateAsStringField, IntegerField
from jarbas.chamber_of_deputies.models import Reimbursement


INTEGERS = (
    'applicant_id',
    'batch_number',
    'congressperson_document',
    'congressperson_id',
    'document_id',
    'document_type',
    'installment',
    'month',
    'subquota_group_id',
    'subquota_number',
    'term',
    'term_id',
    'year'
)

FLOATS = (
    'document_value',
    'reimbursement_value_total',
    'remark_value',
    'total_net_value'
)

TYPES = tuple(chain(
    ((field, IntegerField) for field in INTEGERS),
    ((field, FloatField) for field in FLOATS),
    (('issue_date', DateAsStringField),)
))

RENAME = (
    ('subquota_number', 'subquota_id'),
    ('reimbursement_value_total', 'total_reimbursement_value'),
)


def serialize(row):
    """
    Read the dict generated by the reimbursement command and returns a
    Reimbursement model instance.
    """
    for key, type_ in TYPES:
        value = row.get(key)
        row[key] = type_.deserialize(value)

    for old, new in RENAME:
        row[new] = row.pop(old)

    return Reimbursement(**row)
