# Generated by Django 2.0.8 on 2018-09-13 03:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamber_of_deputies', '0004_alter_field_names_following_toolbox_renamings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congressperson_name', models.CharField(blank=True, default='', max_length=255)),
                ('congressperson_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('twitter_profile', models.CharField(blank=True, default='', max_length=255)),
                ('secondary_twitter_profile', models.CharField(blank=True, default='', max_length=255)),
                ('facebook_page', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='social_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chamber_of_deputies.SocialMedia'),
        ),
    ]
