# Generated by Django 2.0.8 on 2018-09-13 04:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamber_of_deputies', '0005_create_social_media_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='social_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamber_of_deputies.SocialMedia'),
        )
    ]
