# Generated by Django 2.0.8 on 2018-09-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber_of_deputies', '0007_auto_20180913_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reimbursement',
            name='social_media',
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='congressperson_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Identificador Único do Parlamentar'),
        ),
    ]
