# Generated by Django 2.0.8 on 2018-09-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber_of_deputies', '0008_remove_related_field_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='term',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Número da Legislatura'),
        ),
    ]
