# Generated by Django 2.0.8 on 2018-09-13 13:40

from django.db import migrations


def forwards_func(apps, schema_editor):
    Reimbursement = apps.get_model("chamber_of_deputies", "Reimbursement")
    db_alias = schema_editor.connection.alias
    Reimbursement.objects.using(db_alias).filter(issue_date=None).delete()


def reverse_func(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chamber_of_deputies', '0009_add_index_to_term'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
