# Generated by Django 2.0.8 on 2018-09-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber_of_deputies', '0010_remove_null_issue_date_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='issue_date',
            field=models.DateField(db_index=True, verbose_name='Data de Emissão'),
        ),
    ]
