# Generated by Django 2.1.5 on 2019-01-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber_of_deputies', '0011_make_issue_date_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='party',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Partido'),
        ),
    ]
