{
 "title": "Postgres",
 "tags": [
  "database",
  "postgres"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "pg_static", "legendFormat": "{{short_version}}" }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "pg_settings_max_connections" }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched)"
    }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "pg_settings_seq_page_cost" }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated)"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted)"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "pg_settings_random_page_cost" }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "pg_settings_work_mem_bytes" }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "pg_settings_max_wal_size_bytes" }
   ]
  },
  {
   "title": "Database Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "pg_database_size", "legendFormat": "{{ datname }}" }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_database_xact_commit[5m])",
     "legendFormat": "commits - {{datname }}"
    },
    {
     "expr": "increase(pg_stat_database_xact_rollback[5m])",
     "legendFormat": "rollbacks - {{datname }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pg_stat_activity_count", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Change Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_database_tup_inserted[5m])",
     "legendFormat": "INSERT - {{datname}}"
    },
    {
     "expr": "increase(pg_stat_database_tup_updated[5m])",
     "legendFormat": "UPDATE  - {{datname}}"
    },
    {
     "expr": "increase(pg_stat_database_tup_deleted[5m])",
     "legendFormat": "DELETE  - {{datname}}"
    }
   ]
  },
  {
   "title": "Read Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_database_tup_fetched[5m])",
     "legendFormat": "SELECT (index scan) - {{datname}}"
    },
    {
     "expr": "increase(pg_stat_database_tup_returned[5m])",
     "legendFormat": "SELECT (table scan) -  - {{datname}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{datname!~\"template.*\"} / (pg_stat_database_blks_read + pg_stat_database_blks_hit)",
     "legendFormat": "Cache Hit Rate - {{ datname }}"
    }
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration",
     "legendFormat": "max_tx_duration [{{state}}] - {{datname}}"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_database_tup_inserted[5m])",
     "legendFormat": "Insert - {{datname}}"
    },
    {
     "expr": "increase(pg_stat_database_tup_deleted[5m])",
     "legendFormat": "Delete - {{datname}}"
    },
    {
     "expr": "increase(pg_stat_database_tup_updated[5m])",
     "legendFormat": "Update - {{datname}}"
    }
   ]
  },
  {
   "title": "Fetch data (SELECT)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Return data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_returned != 0",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Buffers (bgwriter)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_bgwriter_buffers_backend[5m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "increase(pg_stat_bgwriter_buffers_alloc[5m])",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "increase(pg_stat_bgwriter_buffers_backend_fsync[5m])",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "increase(pg_stat_bgwriter_buffers_checkpoint[5m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "increase(pg_stat_bgwriter_buffers_clean[5m])",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_database_conflicts[5m])",
     "legendFormat": "conflicts -{{datname}}"
    },
    {
     "expr": "increase(pg_stat_database_deadlocks[5m])",
     "legendFormat": "deadlocks -{{datname}}"
    }
   ]
  },
  {
   "title": "Lock Tables",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pg_locks_count", "legendFormat": "{{mode}} - {{datname}}" }
   ]
  },
  {
   "title": "Temp File",
   "type": "graph",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_database_temp_bytes[5m])",
     "legendFormat": "Temp Bytes - {{datname}}"
    }
   ]
  },
  {
   "title": "Tablespace size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "pg_tablespace_size", "legendFormat": "{{ tablespace }}" }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pg_slow_queries" }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(pg_stat_bgwriter_checkpoint_write_time[5m])",
     "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
    },
    {
     "expr": "increase(pg_stat_bgwriter_checkpoint_sync_time[5m])",
     "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
    }
   ]
  }
 ]
}