{
 "title": "Process monitoring",
 "tags": [ "OS" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "processes",
    "query": "label_values(namedprocess_namegroup_cpu_seconds_total,groupname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Top 10 by number of process",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, namedprocess_namegroup_num_procs{groupname=~\"$processes\"})",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top 10 CPU users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum((irate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\"}[5m]))) by (groupname))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top 10 disk readers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, increase(namedprocess_namegroup_read_bytes_total{groupname=~\"$processes\"}[5m]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top 10 disk writers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, increase(namedprocess_namegroup_write_bytes_total{groupname=~\"$processes\"}[5m]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top 10 resident memory consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\"})",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top 10 swap consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"swapped\"})",
     "legendFormat": "{{groupname}}"
    }
   ]
  }
 ]
}