#!/usr/bin/env python3

import pip

pip_major_version = int(pip.__version__.split('.')[0])

if pip_major_version >= 10:
    pip._internal.main(
        ['install', '--upgrade', '-r', 'rosie/requirements.txt'])
else:
    pip.main(['install', '--upgrade', '-r', 'rosie/requirements.txt'])
