from celery import shared_task

from jarbas.core.models import Reimbursement


@shared_task
def create_or_update_reimbursement(row):
    """
    :param row: (dict) key/values maching Reimbursement model
    """
    data = transform_row(row)
    kwargs = dict(document_id=data['document_id'], defaults=data)
    Reimbursement.objects.update_or_create(**kwargs)


def transform_row(row):
    """Read the dict generated by rows and fix some keys"""
    rename = (
        ('subquota_number', 'subquota_id'),
        ('reimbursement_value_total', 'total_reimbursement_value')
    )
    for old, new in rename:
        row[new] = row.pop(old)

    return row
