# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField(verbose_name='Document ID')),
                ('congressperson_name', models.CharField(max_length=64, verbose_name='Congressperson name')),
                ('congressperson_id', models.IntegerField(verbose_name='Congressperson ID')),
                ('congressperson_document', models.IntegerField(verbose_name='Congressperson document')),
                ('term', models.IntegerField(verbose_name='Term')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('party', models.CharField(max_length=16, verbose_name='Party')),
                ('term_id', models.IntegerField(verbose_name='Term ID')),
                ('subquota_number', models.IntegerField(verbose_name='Subquote ID')),
                ('subquota_description', models.CharField(max_length=64, verbose_name='Subquota descrition')),
                ('subquota_group_id', models.IntegerField(verbose_name='Subquota group ID')),
                ('subquota_group_description', models.CharField(max_length=64, verbose_name='Subquota group description')),
                ('supplier', models.CharField(max_length=128, verbose_name='Supplier')),
                ('cnpj_cpf', models.CharField(max_length=14, verbose_name='CNPJ or CPF')),
                ('document_number', models.CharField(max_length=64, verbose_name='Document number')),
                ('document_type', models.IntegerField(verbose_name='Document type')),
                ('issue_date', models.DateTimeField(blank=True, null=True, verbose_name='Issue date')),
                ('document_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Document value')),
                ('remark_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Remark value')),
                ('net_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Net value')),
                ('month', models.IntegerField(verbose_name='Month')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('installment', models.IntegerField(verbose_name='Installment')),
                ('passenger', models.CharField(max_length=64, verbose_name='Passenger')),
                ('leg_of_the_trip', models.CharField(max_length=64, verbose_name='Leg of the trip')),
                ('batch_number', models.IntegerField(verbose_name='Batch number')),
                ('reimbursement_number', models.IntegerField(verbose_name='Reimbursement number')),
                ('reimbursement_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Reimbusrsement value')),
                ('applicant_id', models.IntegerField(verbose_name='Applicant ID')),
                ('source', models.CharField(blank=True, db_index=True, max_length=16, null=True, verbose_name='CSV file source')),
                ('line', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Line # in the source')),
            ],
        ),
    ]
