# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_some_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='receipt_url',
            field=models.URLField(blank=True, default=None, max_length=16, null=True, verbose_name='Receipt URL'),
        ),
    ]
