# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_receipt_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='receipt_url_last_update',
            field=models.URLField(db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='Receipt URL Last Update'),
        ),
    ]
