# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_receipt_url_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='receipt_url_last_update',
        ),
        migrations.AddField(
            model_name='document',
            name='receipt_fetched',
            field=models.BooleanField(default=False, verbose_name='Was receipt fetched?'),
        ),
        migrations.AlterField(
            model_name='document',
            name='receipt_url',
            field=models.URLField(blank=True, default=None, max_length=128, null=True, verbose_name='Receipt URL'),
        ),
    ]
