# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lazy_backend_receipt_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Code')),
                ('description', models.CharField(max_length=128, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(db_index=True, max_length=18, verbose_name='CNPJ')),
                ('opening', models.DateField(blank=True, null=True, verbose_name='Opening date')),
                ('legal_entity', models.CharField(blank=True, max_length=128, null=True, verbose_name='Legal entity')),
                ('trade_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Trade name')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Name')),
                ('type', models.CharField(blank=True, max_length=128, null=True, verbose_name='Type')),
                ('status', models.CharField(blank=True, max_length=128, null=True, verbose_name='Status')),
                ('situation', models.CharField(blank=True, max_length=128, null=True, verbose_name='Situation')),
                ('situation_reason', models.CharField(blank=True, max_length=128, null=True, verbose_name='Situation reason')),
                ('situation_date', models.DateField(blank=True, null=True, verbose_name='Situation date')),
                ('special_situation', models.CharField(blank=True, max_length=128, null=True, verbose_name='Special situation')),
                ('special_situation_date', models.CharField(blank=True, max_length=128, null=True, verbose_name='Special situation date')),
                ('responsible_federative_entity', models.CharField(blank=True, max_length=128, null=True, verbose_name='Responsible federative entity')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Address')),
                ('number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Number')),
                ('additional_address_details', models.CharField(blank=True, max_length=128, null=True, verbose_name='Additional address details')),
                ('neighborhood', models.CharField(blank=True, max_length=128, null=True, verbose_name='Neighborhood')),
                ('zip_code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Zip code')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=128, null=True, verbose_name='State')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='Phone')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Last updated')),
                ('main_activity', models.ManyToManyField(related_name='main', to='core.Activity')),
                ('secondary_activity', models.ManyToManyField(related_name='secondary', to='core.Activity')),
            ],
        ),
    ]
