# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=167, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='document',
            name='congressperson_name',
            field=models.CharField(max_length=33, verbose_name='Congressperson name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_number',
            field=models.CharField(max_length=30, verbose_name='Document number'),
        ),
        migrations.AlterField(
            model_name='document',
            name='leg_of_the_trip',
            field=models.CharField(max_length=100, verbose_name='Leg of the trip'),
        ),
        migrations.AlterField(
            model_name='document',
            name='party',
            field=models.CharField(db_index=True, max_length=7, verbose_name='Party'),
        ),
        migrations.AlterField(
            model_name='document',
            name='passenger',
            field=models.CharField(max_length=59, verbose_name='Passenger'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subquota_description',
            field=models.CharField(max_length=56, verbose_name='Subquota descrition'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subquota_group_description',
            field=models.CharField(max_length=20, verbose_name='Subquota group description'),
        ),
        migrations.AlterField(
            model_name='document',
            name='supplier',
            field=models.CharField(max_length=100, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='additional_address_details',
            field=models.CharField(blank=True, max_length=143, null=True, verbose_name='Additional address details'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=58, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='legal_entity',
            field=models.CharField(blank=True, max_length=72, null=True, verbose_name='Legal entity'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, max_length=144, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Neighborhood'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='responsible_federative_entity',
            field=models.CharField(blank=True, max_length=38, null=True, verbose_name='Responsible federative entity'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='situation',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Situation'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='situation_reason',
            field=models.CharField(blank=True, max_length=44, null=True, verbose_name='Situation reason'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='special_situation',
            field=models.CharField(blank=True, max_length=51, null=True, verbose_name='Special situation'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='special_situation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Special situation date'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='trade_name',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Trade name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip code'),
        ),
    ]
