# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_subquota_description_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Issue date'),
        ),
    ]
