# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_use_date_not_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, verbose_name='Year')),
                ('applicant_id', models.IntegerField(db_index=True, verbose_name='Applicant ID')),
                ('document_id', models.IntegerField(db_index=True, verbose_name='Document ID')),
                ('total_reimbursement_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Total reimbusrsement value')),
                ('total_net_value', models.DecimalField(db_index=True, decimal_places=3, max_digits=10, verbose_name='Total net value')),
                ('reimbursement_numbers', models.CharField(max_length=140, verbose_name='Reimbursement numbers')),
                ('congressperson_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Congressperson ID')),
                ('congressperson_name', models.CharField(blank=True, db_index=True, max_length=140, null=True, verbose_name='Congressperson name')),
                ('congressperson_document', models.IntegerField(blank=True, null=True, verbose_name='Congressperson document')),
                ('party', models.CharField(db_index=True, max_length=7, verbose_name='Party')),
                ('state', models.CharField(db_index=True, max_length=2, verbose_name='State')),
                ('term_id', models.IntegerField(verbose_name='Term ID')),
                ('term', models.IntegerField(verbose_name='Term')),
                ('subquota_id', models.IntegerField(db_index=True, verbose_name='Subquota ID')),
                ('subquota_description', models.CharField(max_length=140, verbose_name='Subquota descrition')),
                ('subquota_group_id', models.IntegerField(blank=True, null=True, verbose_name='Subquota group ID')),
                ('subquota_group_description', models.CharField(blank=True, max_length=140, null=True, verbose_name='Subquota group description')),
                ('supplier', models.CharField(max_length=140, verbose_name='Supplier')),
                ('cnpj_cpf', models.CharField(blank=True, db_index=True, max_length=14, null=True, verbose_name='CNPJ or CPF')),
                ('document_type', models.IntegerField(verbose_name='Document type')),
                ('document_number', models.CharField(max_length=140, verbose_name='Document number')),
                ('document_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Document value')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue date')),
                ('month', models.IntegerField(db_index=True, verbose_name='Month')),
                ('remark_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Remark value')),
                ('net_values', models.CharField(max_length=140, verbose_name='Net values')),
                ('installment', models.IntegerField(blank=True, null=True, verbose_name='Installment')),
                ('batch_number', models.IntegerField(verbose_name='Batch number')),
                ('reimbursement_values', models.CharField(blank=True, max_length=140, null=True, verbose_name='Reimbusrsement values')),
                ('passenger', models.CharField(blank=True, max_length=140, null=True, verbose_name='Passenger')),
                ('leg_of_the_trip', models.CharField(blank=True, max_length=140, null=True, verbose_name='Leg of the trip')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reimbursement',
            unique_together=set([('year', 'applicant_id', 'document_id')]),
        ),
    ]
