# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 13:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_create_model_reimbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='probability',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='Probability'),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='suspicions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Suspicions'),
        ),
    ]
