# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_make_issue_date_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='document',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
