# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cleanup_remove_old_api'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplier',
            new_name='Company',
        ),
    ]
