# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_supplier_to_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='receipt_fetched',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Was the receipt URL fetched?'),
        ),
    ]
