# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_make_reciept_fetched_a_db_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='document_id',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Document ID'),
        ),
        migrations.AlterUniqueTogether(
            name='reimbursement',
            unique_together=set([]),
        ),
    ]
