# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_unique_together_from_reimbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='last_update',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last update'),
        ),
    ]
