# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_historicalreimbursement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reimbursement',
            options={'ordering': ('-year', '-issue_date'), 'verbose_name': 'reimbursement', 'verbose_name_plural': 'reimbursements'},
        ),
    ]
