# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 18:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_order_reimbursements_by_year_and_issue_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalreimbursement',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical reembolso'},
        ),
        migrations.AlterModelOptions(
            name='reimbursement',
            options={'ordering': ('-year', '-issue_date'), 'verbose_name': 'reembolso', 'verbose_name_plural': 'reembolsos'},
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='applicant_id',
            field=models.IntegerField(db_index=True, verbose_name='Identificador do Solicitante'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='available_in_latest_dataset',
            field=models.BooleanField(default=True, verbose_name='Disponível na Câmara dos Deputados'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='batch_number',
            field=models.IntegerField(verbose_name='Número do Lote'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='cnpj_cpf',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, verbose_name='CNPJ ou CPF'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='congressperson_document',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número da  Carteira Parlamentar'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='congressperson_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Identificador Único do Parlamentar'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='congressperson_name',
            field=models.CharField(blank=True, db_index=True, max_length=140, null=True, verbose_name='Nome do Parlamentar'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='document_id',
            field=models.IntegerField(db_index=True, verbose_name='Número do Reembolso'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='document_number',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Número do Documento'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='document_type',
            field=models.IntegerField(verbose_name='Indicativo de Tipo de Documento Fiscal'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='document_value',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Valor do Documento'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='installment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número da Parcela'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='issue_date',
            field=models.DateField(verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='last_update',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Atualizado no Jarbas em'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='leg_of_the_trip',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Trecho'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='month',
            field=models.IntegerField(db_index=True, verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='net_values',
            field=models.CharField(max_length=140, verbose_name='Valores Líquidos dos Ressarcimentos'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='party',
            field=models.CharField(blank=True, db_index=True, max_length=7, null=True, verbose_name='Partido'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='passenger',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Passageiro'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='probability',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='Probabilidade'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='receipt_fetched',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Tentamos aessar a URL do documento fiscal?'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='receipt_url',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='URL do Documento Fiscal'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='reimbursement_numbers',
            field=models.CharField(max_length=140, verbose_name='Números dos Ressarcimentos'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='reimbursement_values',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Valores dos Ressarcimentos'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='remark_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Valor da Glosa'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='subquota_description',
            field=models.CharField(max_length=140, verbose_name='Descrição da Subcota'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='subquota_group_description',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Descrição da Especificação da Subcota'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='subquota_group_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número da Especificação da Subcota'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='subquota_id',
            field=models.IntegerField(db_index=True, verbose_name='Número da Subcota'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='supplier',
            field=models.CharField(max_length=140, verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='suspicions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Suspeitas'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='term',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número da  Legislatura'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='term_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código da Legislatura'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='total_net_value',
            field=models.DecimalField(db_index=True, decimal_places=3, max_digits=10, verbose_name='Valor Líquido'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='total_reimbursement_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Valor da Restituição'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='year',
            field=models.IntegerField(db_index=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='applicant_id',
            field=models.IntegerField(db_index=True, verbose_name='Identificador do Solicitante'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='available_in_latest_dataset',
            field=models.BooleanField(default=True, verbose_name='Disponível na Câmara dos Deputados'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='batch_number',
            field=models.IntegerField(verbose_name='Número do Lote'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='cnpj_cpf',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, verbose_name='CNPJ ou CPF'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='congressperson_document',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número da  Carteira Parlamentar'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='congressperson_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Identificador Único do Parlamentar'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='congressperson_name',
            field=models.CharField(blank=True, db_index=True, max_length=140, null=True, verbose_name='Nome do Parlamentar'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='document_id',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Número do Reembolso'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='document_number',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Número do Documento'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='document_type',
            field=models.IntegerField(verbose_name='Indicativo de Tipo de Documento Fiscal'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='document_value',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Valor do Documento'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='installment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número da Parcela'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='issue_date',
            field=models.DateField(verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='last_update',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado no Jarbas em'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='leg_of_the_trip',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Trecho'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='month',
            field=models.IntegerField(db_index=True, verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='net_values',
            field=models.CharField(max_length=140, verbose_name='Valores Líquidos dos Ressarcimentos'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='party',
            field=models.CharField(blank=True, db_index=True, max_length=7, null=True, verbose_name='Partido'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='passenger',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Passageiro'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='probability',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='Probabilidade'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='receipt_fetched',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Tentamos aessar a URL do documento fiscal?'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='receipt_url',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='URL do Documento Fiscal'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='reimbursement_numbers',
            field=models.CharField(max_length=140, verbose_name='Números dos Ressarcimentos'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='reimbursement_values',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Valores dos Ressarcimentos'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='remark_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Valor da Glosa'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='subquota_description',
            field=models.CharField(max_length=140, verbose_name='Descrição da Subcota'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='subquota_group_description',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Descrição da Especificação da Subcota'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='subquota_group_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número da Especificação da Subcota'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='subquota_id',
            field=models.IntegerField(db_index=True, verbose_name='Número da Subcota'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='supplier',
            field=models.CharField(max_length=140, verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='suspicions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Suspeitas'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='term',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número da  Legislatura'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='term_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código da Legislatura'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='total_net_value',
            field=models.DecimalField(db_index=True, decimal_places=3, max_digits=10, verbose_name='Valor Líquido'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='total_reimbursement_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Valor da Restituição'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='year',
            field=models.IntegerField(db_index=True, verbose_name='Ano'),
        ),
    ]
