# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_make_issue_date_an_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='congressperson_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Identificador Único do Parlamentar'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='party',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Partido'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='total_net_value',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Valor Líquido'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='congressperson_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Identificador Único do Parlamentar'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='party',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Partido'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='total_net_value',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Valor Líquido'),
        ),
    ]
