# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_unused_indexes'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='reimbursement',
            index_together=set([('year', 'issue_date', 'id')]),
        ),
    ]
