# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_index_together_for_reimbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='history_type',
            field=models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
    ]
