# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20170613_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='history_type',
            field=models.CharField(choices=[('+', 'Criado'), ('~', 'Modificado'), ('-', 'Excluído')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='subquota_description',
            field=models.CharField(db_index=True, max_length=140, verbose_name='Descrição da Subcota'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='subquota_description',
            field=models.CharField(db_index=True, max_length=140, verbose_name='Descrição da Subcota'),
        ),
    ]
