# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20170629_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(db_index=True, verbose_name='Tweet ID')),
                ('reimbursement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Reimbursement')),
            ],
            options={
                'ordering': ('-status',),
            },
        ),
    ]
