# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_tweet_status_to_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreimbursement',
            name='reimbursement_text',
            field=models.TextField(blank=True, null=True, verbose_name='OCR'),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='reimbursement_text',
            field=models.TextField(blank=True, null=True, verbose_name='OCR'),
        ),
    ]
