# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 20:19
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20170728_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreimbursement',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
