# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 02:37
from __future__ import unicode_literals

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_search_vector_to_reimbursement'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reimbursement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='core_reimbu_search__ba9b2f_gin'),
        ),
    ]
