# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 16:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_create_gin_index_with_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='probability',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=6, null=True, verbose_name='Probabilidade'),
        ),
        migrations.AlterField(
            model_name='historicalreimbursement',
            name='suspicions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True, verbose_name='Suspeitas'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='probability',
            field=models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=6, null=True, verbose_name='Probabilidade'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='suspicions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True, verbose_name='Suspeitas'),
        ),
    ]
