# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_create_gin_index_with_search_vector'),
    ]

    database_operations = [
        migrations.AlterModelTable('Reimbursement', 'chamber_of_deputies_reimbursement'),
        migrations.AlterModelTable('HistoricalReimbursement', 'chamber_of_deputies_historicalreimbursement'),
        migrations.AlterModelTable('Tweet', 'chamber_of_deputies_tweet'),
    ]

    state_operations = [
        migrations.DeleteModel(
            name='Reimbursement',
        ),
        migrations.DeleteModel(
            name='HistoricalReimbursement',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
