# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_create_gin_index_with_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreimbursement',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Reimbursement',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='reimbursement',
        ),
        migrations.DeleteModel(
            name='HistoricalReimbursement',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
